version: '3.8'
 
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-cont
    #restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/job_portal
    depends_on:
      - mongo
  mongo:
      container_name: mongodb-cont
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - 27017:27017